name: Deploy Backend to Lambda

on:
  push:
    paths:
      - 'lambda tests/**'
      - '.github/workflows/deploy-backend.yml'
      - 'terraform/**'
    branches:
      - main

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Zip Lambda code
        run: |
          cd "lambda tests"
          zip -r ../lambda.zip .

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name UpdateVisitorCount \
            --zip-file fileb://lambda.zip
